"""
query.py — a chat CLI over your screenshot history.

Two-step flow per turn:
  1. Gemma reads your question and turns it into search terms (+ an
     optional time range), since raw conversational questions don't
     match well against FTS5 keyword search directly.
  2. Those terms retrieve candidate rows from the local index, and a
     second Gemma call synthesizes an answer grounded only in what was
     retrieved — citing the timestamp of each entry it draws from.

Run it:
    python query.py
Exit:
    type 'exit', 'quit', or Ctrl+C
"""

import argparse
import json
import logging
from datetime import datetime, timedelta

import ollama

import db

DEBUG = False

QUERY_MODEL = "gemma4:e4b"
MAX_RESULTS = 8

INTENT_PROMPT = """You turn a user's question about their screen history into a search query.

Today's date/time is: {now}

Respond with ONLY a JSON object, no markdown, no preamble:
{{"keywords": "space-separated search terms, just the important words",
  "since": "ISO 8601 datetime to search from, or null if no time constraint",
  "until": "ISO 8601 datetime to search until, or null if no time constraint"}}

Rules for keywords:
- Only include words that are specific, searchable content: names, numbers, IDs,
  app names, topics, companies.
- NEVER include generic words about the action itself, like "doing", "happening",
  "working on", "looking at" — these won't match anything and will cause the
  search to fail. If the question has no specific content to search for, use
  an empty string "" for keywords and rely on the time range instead.

Rules for time ranges:
- If the question mentions a specific time (e.g. "at 2:45pm"), use a buffer of
  at least 20 minutes on each side, not an exact narrow window — the user's
  sense of time is approximate and capture timing won't line up exactly.
- If the question mentions a period (morning, afternoon, yesterday), use that
  period's natural bounds.

Using the conversation:
- The question may be a follow-up that only makes sense given what was already
  discussed (e.g. "tell me more about that", "what about the one before it",
  "when was that"). Use the conversation below to figure out what the user is
  actually referring to, and build keywords/time range for THAT subject —
  pull specific names or topics from the earlier turns when the new question
  leans on them.

{history_block}Examples:
"when did I see that invoice number" -> {{"keywords": "invoice number", "since": null, "until": null}}
"what was I doing yesterday afternoon" -> {{"keywords": "", "since": "<yesterday 12:00>", "until": "<yesterday 18:00>"}}
"that email from acme this morning" -> {{"keywords": "email acme", "since": "<today 00:00>", "until": "<now>"}}
"what was i doing at 2:45pm today" -> {{"keywords": "", "since": "<today 14:25>", "until": "<today 15:05>"}}
"what did I schedule on my calendar today" -> {{"keywords": "calendar schedule event", "since": "<today 00:00>", "until": "<now>"}}
"what was that summer camp thing i saw earlier today" -> {{"keywords": "summer camp", "since": "<today 00:00>", "until": "<now>"}}

User's question: {question}"""

SYNTHESIS_PROMPT = """You are Hindsight, an assistant that helps someone recall things they saw on their own screen.

You are given a list of retrieved log entries below, each with a timestamp, the app, and what was extracted from that screenshot. Answer the user's question about their screen history using ONLY these entries — don't guess or invent anything not present here. If nothing relevant was retrieved, say so plainly and suggest they try rephrasing.

This is an ongoing conversation. Use the conversation so far to understand follow-up questions and to refer back to things you already told the user (e.g. "the invoice I mentioned earlier"). It's fine to answer a question that's purely about the conversation itself (like "what did I just ask?") from the conversation alone. But any *new* facts about what was on their screen must come from the retrieved entries below, not from memory.

Write in a natural, conversational way. Only mention *when* something happened
when it actually matters to the answer (e.g. the user asked about a specific
time, or the timing is the point) — don't tag every sentence with a time. When
you do mention a time, use a natural human-readable form like "around 3:26pm"
or "this afternoon", never the raw timestamp. Note: Zen is a web browser, not an IDE.

{history_block}Retrieved entries:
{context}

User's current question: {question}"""

logging.basicConfig(level=logging.WARNING)
log = logging.getLogger("query")


def resolve_datetime_placeholder(val: str | None) -> str | None:
    """
    Resolves relative time placeholders like '<today 00:00>', '<yesterday 14:00>',
    and '<now>' generated by the model into actual ISO 8601 strings.
    """
    if not val:
        return None
    val = val.strip()
    if not (val.startswith("<") and val.endswith(">")):
        return val

    placeholder = val[1:-1].lower().strip()
    now = datetime.now()

    if placeholder == "now":
        return now.isoformat()

    if placeholder.startswith("today "):
        time_part = placeholder.replace("today ", "").strip()
        try:
            h, m = map(int, time_part.split(":"))
            return now.replace(hour=h, minute=m, second=0, microsecond=0).isoformat()
        except Exception:
            pass

    if placeholder.startswith("yesterday "):
        time_part = placeholder.replace("yesterday ", "").strip()
        try:
            h, m = map(int, time_part.split(":"))
            yesterday = now - timedelta(days=1)
            return yesterday.replace(hour=h, minute=m, second=0, microsecond=0).isoformat()
        except Exception:
            pass

    return None


def format_history(history: list | None, max_messages: int = 8) -> str:
    """Render the recent conversation as plain text for prompting. Only the
    last `max_messages` turns are kept so the prompt stays bounded."""
    if not history:
        return ""
    recent = history[-max_messages:]
    lines = []
    for m in recent:
        role = "User" if m.get("role") == "user" else "Hindsight"
        content = (m.get("content") or "").strip()
        if content:
            lines.append(f"{role}: {content}")
    return "\n".join(lines)


def _history_block(history: list | None, heading: str) -> str:
    """A labeled conversation block for a prompt, or "" when there's no
    history yet — so the first turn reads exactly as it did before."""
    text = format_history(history)
    if not text:
        return ""
    return f"{heading}\n{text}\n\n"


def extract_search_terms(question: str, history: list | None = None) -> dict:
    """Ask Gemma to turn a conversational question into FTS5-friendly terms."""
    now = datetime.now().isoformat()
    history_block = _history_block(history, "Conversation so far (oldest first):")
    prompt = INTENT_PROMPT.format(now=now, question=question, history_block=history_block)

    if DEBUG:
        print(f"\n[debug] intent prompt sent to {QUERY_MODEL}:\n{prompt}\n")

    response = ollama.generate(
        model=QUERY_MODEL,
        prompt=prompt,
        format="json",
        options={"temperature": 0},
    )
    text = response["response"].strip()

    if DEBUG:
        print(f"[debug] raw intent response:\n{text}\n")

    try:
        terms = json.loads(text)
    except json.JSONDecodeError:
        log.warning("Intent parsing returned non-JSON, falling back to raw question as keywords")
        terms = {"keywords": question, "since": None, "until": None}

    if isinstance(terms, dict):
        terms["since"] = resolve_datetime_placeholder(terms.get("since"))
        terms["until"] = resolve_datetime_placeholder(terms.get("until"))

    if DEBUG:
        print(f"[debug] parsed terms (resolved): {terms}\n")

    return terms


def sanitize_fts_query(query_str: str) -> str:
    """
    Sanitize a keyword search string to be safe for SQLite FTS5.
    Wraps each term in double quotes, escaping any double quotes within the term.
    Allows trailing asterisks (*) for prefix search.
    """
    terms = []
    for token in query_str.split():
        is_prefix = False
        if token.endswith("*") and len(token) > 1:
            is_prefix = True
            token = token[:-1]

        clean_token = token.replace('"', '""')

        if clean_token:
            quoted = f'"{clean_token}"'
            if is_prefix:
                quoted += "*"
            terms.append(quoted)

    return " ".join(terms)


def retrieve(terms: dict) -> list:
    keywords = terms.get("keywords") or ""
    since = terms.get("since")
    until = terms.get("until")

    if not keywords.strip():
        rows = db.get_by_time_range(since=since, until=until, limit=MAX_RESULTS)
        if DEBUG:
            print(f"[debug] no keywords -> browsing time window, since={since} until={until}")
            print(f"[debug] {len(rows)} row(s) found\n")
        return rows

    sanitized = sanitize_fts_query(keywords)

    try:
        rows = db.search_text(sanitized, since=since, until=until, limit=MAX_RESULTS)
        if not rows and " " in sanitized:
            or_query = " OR ".join(sanitized.split())
            if DEBUG:
                print(f"[debug] strict FTS5 search returned 0 matches, trying OR search: '{or_query}'")
            rows = db.search_text(or_query, since=since, until=until, limit=MAX_RESULTS)
    except Exception as e:
        log.warning("FTS5 query failed (%s), falling back to time-window or recent entries", e)
        if since or until:
            rows = db.get_by_time_range(since=since, until=until, limit=MAX_RESULTS)
        else:
            rows = db.get_recent(limit=MAX_RESULTS)

    if DEBUG:
        print(f"[debug] FTS5 search: keywords='{keywords}' (sanitized='{sanitized}') since={since} until={until}")
        print(f"[debug] {len(rows)} row(s) matched\n")

    if not rows and (since or until):
        rows = db.get_by_time_range(since=since, until=until, limit=MAX_RESULTS)
        if DEBUG:
            print(f"[debug] keyword match empty, falling back to time-window browse: {len(rows)} row(s)\n")

    return rows


def humanize_timestamp(ts: str | None) -> str:
    """Render an ISO timestamp as something a person would say, e.g.
    'Jul 18, 3:26pm'. Falls back to the raw value if it won't parse."""
    if not ts:
        return "unknown time"
    try:
        dt = datetime.fromisoformat(ts)
    except (ValueError, TypeError):
        return ts
    return dt.strftime("%b %d, %I:%M%p").replace(" 0", " ").lstrip("0").replace("AM", "am").replace("PM", "pm")


def format_context(rows: list) -> str:
    if not rows:
        return "(no matching entries found)"
    lines = []
    for r in rows:
        lines.append(
            f"- [{humanize_timestamp(r['captured_at'])}] app={r['app_name'] or 'unknown'} | "
            f"summary: {r['summary']} | text: {r['raw_text']}"
        )
    return "\n".join(lines)


def synthesize_answer(question: str, rows: list, history: list | None = None) -> str:
    return "".join(stream_synthesize_answer(question, rows, history=history)).strip()


def stream_synthesize_answer(question: str, rows: list, history: list | None = None):
    context = format_context(rows)
    history_block = _history_block(history, "Conversation so far (oldest first):")

    if DEBUG:
        print(f"[debug] context sent to synthesis:\n{context}\n")

    stream = ollama.generate(
        model=QUERY_MODEL,
        prompt=SYNTHESIS_PROMPT.format(
            context=context, question=question, history_block=history_block
        ),
        options={"temperature": 0},
        stream=True,
    )
    for chunk in stream:
        token = chunk.get("response", "")
        if token:
            yield token


def ask(question: str, history: list | None = None) -> str:
    terms = extract_search_terms(question, history=history)
    rows = retrieve(terms)
    return synthesize_answer(question, rows, history=history)


def run():
    global DEBUG
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug", action="store_true", help="print intent parsing, retrieval, and context at each step")
    args = parser.parse_args()
    DEBUG = args.debug

    print(f"Hindsight — ask about your screen history (model: {QUERY_MODEL})")
    if DEBUG:
        print("(debug mode on)")
    print("Type 'exit' or 'quit' to leave.\n")

    history: list[dict] = []
    while True:
        try:
            question = input("you> ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nbye")
            break

        if not question:
            continue
        if question.lower() in ("exit", "quit"):
            print("bye")
            break

        answer = ask(question, history=history)
        print(f"\nhindsight> {answer}\n")
        history.append({"role": "user", "content": question})
        history.append({"role": "assistant", "content": answer})


if __name__ == "__main__":
    run()